export const IMAGES = {
  logo: require('../assests/images/logo.png'),
  login: require('../assests/images/login.png'),
  logo2: require('../assests/images/logo2.png'),
  girl: require('../assests/images/girl.jpg'),
  girl2: require('../assests/images/girl2.jpg'),
  girl3: require('../assests/images/girl3.jpg'),
  girl4: require('../assests/images/girl4.jpg'),
  girl5: require('../assests/images/girl5.jpeg'),
  girl6: require('../assests/images/girl6.jpg'),
  girl7: require('../assests/images/girl7.jpg'),
  girl8: require('../assests/images/girl8.jpg'),
  girl9: require('../assests/images/girl9.jpg'),
  profile: require('../assests/images/profile1.jpg'),
  emptyprofile: require('../assests/images/emptyprofile.png'),
  google_logo: require('../assests/images/Google.png'),
};
export const SIZE = {
  SMALLTEXT: 12,
  EXTRASMALL: 14,
  SMALL: 16,
  MEDIUM: 18,
  LARGE: 20,
  MEDIUMLARGE: 22,
  EXTRALARGE: 26,
};
export const FONTS = {
  SEMIBOLD_600: 'Poppins-SemiBold',
  REGULAR: 'Poppins-Light',
  MEDIUM: 'Poppins-Medium',
};
export const COLORS = {
  PRIMARY_600: '#024CAA',
  PRIMARY_800: '#0B2F9F',
  PRIMARY_700: '#1230AE',
  NATURAL_WHITE: '#FFFFFF',
  PRIMARY_100: '#DBF0FF',
  NEUTRAL_50: '#F4F7FA',
  NEUTRAL_100: '#EFF2F5',
  NEUTRAL_200: '#DEE4EB',
  NEUTRAL_300: '#C3CCD6',
  NEUTRAL_400: '#A8B5C2',
  NEUTRAL_500: '#505861',
  NEUTRAL_600: '#6A7682',
  NEUTRAL_700: '#505861',
  NEUTRAL_800: 'rgba(53, 59, 65, 1)',
  NEUTRAL_900: '#1B1D20',
};
export const LINEHEIGHT = {
  SMALL: 17.6,
  MEDIUM: 18,
  EXTRAMEDUIM: 21,
  REGULAR: 22,
  LARGE: 24,
  MEDIUMLARGE: 27,
  EXTRAMEDIUMLARGE: 30,
  EXTRALARGE: 39,
  DOUBLELARGE: 40,
};
